name: deploy image to ghcr
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: get app code
        uses: actions/checkout@v4

      - name: get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: login to gitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_TOKEN}}

      - name: build image
        run: |
          docker build . --tag ghcr.io/yat0ya/container-calculator:${{ steps.package-version.outputs.current-version }}

      - name: publish image
        run: |
          docker push ghcr.io/yat0ya/container-calculator:${{ steps.package-version.outputs.current-version }}
